spring.application.name=ko-fi-orch

ko-fi-orch.source.base-url=${SOURCE_API_BASE_URL:http://localhost:9090}

ko-fi-orch.upload-api.base-url=${UPLOAD_API_BASE_URL:http://localhost:9091}

ko-fi-orch.s3.region=${AWS_REGION:eu-west-1}
ko-fi-orch.s3.bucket=${S3_BUCKET:ko-fi-orch-uploads}
ko-fi-orch.s3.presign-duration=15m
